---
hosts: localhost
become: false
gather_facts: false

tasks:
  - name: start cassandra hosts
    virt:
      name: "{{ item }}"
      state: running
      uri: 'qemu+ssh://fabiom@libvirt.example.com/system'
    loop:
      - "{{ groups['cassandra'] }}"
